package componentized:components;

world extract-wit {
    export componentized:component/wit@0.0.0-dev;
}

world filesystem-loader {
    import wasi:filesystem/types@0.3.0;
    import wasi:filesystem/preopens@0.3.0;
    export componentized:component/types@0.0.0-dev;
    export componentized:component/path-loader@0.0.0-dev;
}

world http-loader {
    import componentized:http/client@0.1.0-dev;
    export componentized:component/types@0.0.0-dev;
    export componentized:component/path-loader@0.0.0-dev;
}

world oci-loader {
    import componentized:oci/client@0.0.0-dev;
    export componentized:component/types@0.0.0-dev;
    export componentized:component/path-loader@0.0.0-dev;
}

world path-loader {
    import filesystem-loader: interface {
        use componentized:component/types@0.0.0-dev.{component, error};
        load: async func(path: string) -> result<component, error>;
    }
    import http-loader: interface {
        use componentized:component/types@0.0.0-dev.{component, error};
        load: async func(path: string) -> result<component, error>;
    }
    import oci-loader: interface {
        use componentized:component/types@0.0.0-dev.{component, error};
        load: async func(path: string) -> result<component, error>;
    }

    export componentized:component/types@0.0.0-dev;
    export componentized:component/path-loader@0.0.0-dev;
}

world wac-loader {
    export componentized:component/types@0.0.0-dev;
    export componentized:component/wac-loader@0.0.0-dev;
}
