interface path-loader {
    use types.{component, error};

    load: async func(path: string) -> result<component, error>;
}

interface wac-loader {
    use types.{component, error};

    plug: async func(socket: component, plugs: list<component>) -> result<component, error>;
}