interface path-loader {
    use types.{component, error};

    load: async func(path: string) -> result<component, error>;
}

interface wac-loader {
    use types.{component, error};

    type %package = string;
    type dependency = tuple<%package, component>;

    variant plan {
        wac(string),
        // TODO add graph model
    }

    plug: async func(socket: component, plugs: list<component>) -> result<component, error>;
    compose: async func(plan: plan, dependencies: list<dependency>) -> result<component, error>;
}