package componentized:component@0.1.1-dev;

/// Imports every interface in the package, for consumers of the package.
@since(version = 0.1.0)
world imports {
    import types;
    import path-loader;
    import wac-loader;
    import wit;
}
